(define questions
  '(("Pflanze mit bunten Blüten"                        "BLUME")
    ("Schriftliche Nachricht zum Versenden"              "BRIEF")
    ("Heiße, leuchtende Flamme"                         "FEUER")
    ("Fließendes Gewässer, kleiner als ein Strom"       "FLUSS")
    ("Kleines Haustier, das schnurrt"                   "KATZE")
    ("Einteiliges Kleidungsstück"                       "KLEID")
    ("Klänge, Melodien und Rhythmus"                    "MUSIK")
    ("Die dunkle Zeit des Tages"                        "NACHT")
    ("Großes Tier zum Reiten"                           "PFERD")
    ("Großer bewohnter Ort mit vielen Häusern"          "STADT")
    ("Leuchtendes Objekt am Nachthimmel"                "STERN")
    ("Möbelstück mit flacher Oberfläche zum Sitzen"     "TISCH")
    ("Tier mit Federn, das fliegen kann"                "VOGEL")
    ("Weißes Gebilde am Himmel aus Wasserdampf"         "WOLKE")
    ("Untergrund, auf dem man steht oder geht"          "BODEN")))

(define (question-text q)   (car q))
(define (question-answer q) (cadr q))
(define (questions-count)   (length questions))
(define (pick-question idx) (list-ref questions idx))

(define (check-answer correct input)
  (string=? (string-upcase correct) (string-upcase input)))
